version: "3"

volumes:
  db-volume:
  maildir: {}

services:
  mysql:
    build:
      context: ./db
    ports:
      - 3306:3306
    volumes:
      - ./db/var/lib/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    platform: linux/x86_64
  phpfpm:
    build:
      context: ./app
    volumes:
      - ../posse-3rd-laravel-study:/work/backend
    depends_on: ["mysql"]
  nginx:
    build:
      context: ./web
    ports:
      - 80:80
    volumes:
      - ../posse-3rd-laravel-study:/work/backend
    depends_on: ["phpfpm"]
  mail:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - '8025:8025'
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /tmp
    volumes:
      - maildir:/tmp
