version: "3"

volumes:
  db-volume:
  maildir: {}

services:
  mysql:
    platform: linux/amd64
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    volumes:
      - ./container/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./container/db/etc/mysql/conf.d:/etc/mysql/conf.d
      - ./container/db/data:/var/lib/mysql
  phpfpm:
    build:
      context: ./app
    volumes:
      - ../posse-3rd-laravel-study:/work/backend
    depends_on: ["mysql"]
  nginx:
    build:
      context: ./web
    ports:
      - 80:80
    volumes:
      - ../posse-3rd-laravel-study:/work/backend
    depends_on: ["phpfpm"]
  mail:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - '8025:8025'
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /tmp
    volumes:
      - maildir:/tmp
