version: '3'
services:
  nginx: # ここの名前はなんでも大丈夫
    image: nginx:latest
    # nginx:latestイメージを元にビルド
    # docker hubからとってきてる
    # js,html,cssをweb上に表示するだけ⇒php表示できない
    ports:
      - 8080:80
      # localhostの8080番ポートとdockerコンテナの80番ポートをバインド
    volumes:
      # ローカルのリソースをコンテナにマウント
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      # 左側ローカル：右側リモート
      # nginx.confとdefault.confが対応してる
      - ./www/html:/var/www/html
    depends_on:
      - php
      # phpコンテナに依存
      # phpを元にたてますよ
      # 起動する順番

  php:
    build: ./php
    # php/Dockerfileを元にビルド
    # image⇒とってきてるだけ
    # build⇒追加してる。説明書を使ってくれよ
    volumes:
      - ./www/html:/var/www/html
      # www/htmlをコンテナの/var/www/htmlにマウント
    depends_on:
      - mysql
      # dbコンテナに依存

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
      # localhostの3306番ポートとdockerコンテナの3306番ポートをバインド
    volumes:
      - ./mysql/data:/var/lib/mysql
      # ./mysql/dataをコンテナの/var/lib/mysqlにマウント
    environment:
      MYSQL_ROOT_PASSWORD: secret
      # mysqlのルートに入るパスワード

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=secret
    links:
      - mysql
    ports:
        - 8000:80
    volumes:
      - /sessions